databases:
  - name: django_render_db
    region: singapore
    plan: free
    databaseName: sqlite3
    user: django_user

services:
  - type: web
    name: django_render
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: 'postgresql://django_user:8zAhzhsSfBrOKlAx1Fi4xJEuIeWRtGOm@dpg-cu8r94aj1k6c73f133fg-a/sqlite3_4cnz'
        fromDatabase:
          name: sqlite3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
  